# Generated by Django 5.0.5 on 2024-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
