# Generated by Django 5.0.5 on 2024-05-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
